jobs:
  run_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.5'
          architecture: 'x64'
      - run: make install
      - run: make test
